// <auto-generated />
namespace TecgurusAdvanced2021.MVC_Prueba.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTeacher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTeacher));
        
        string IMigrationMetadata.Id
        {
            get { return "202104101745423_AddTeacher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
